#!/bin/bash

###############################################
# Fancy printing 
###############################################
# Some colors for fancy prints
RED='\033[0;31m'        # Red
GREEN='\033[0;32m'      # Green
NC='\033[0m'            # No Color
    
if [ "$OS" = "Mac" ]; then
    source $MYUTILS_HOME/dot-files/mac_terminal_config/set_colors.sh
fi

function print_divider() {
    # Prints 40 *'s to be used as a divider
    printf "\n****************************************\n"
}

function print_header() {
    # Prints a header between two dividers. 
    # $1: The string to be printed
    print_divider
    printf "$1"
    print_divider
}

function print_color() {
    # Prints a given string in a given color
    # $1: The string to be printed
    # $2: The given color
    printf "${2}${1}${NC}"
}
