#!/bin/bash

# Import Functions
# $1 the dir the functions live in 
function import_functions {
    DIR=$1
	# iterate through the files in the 'functions' folder
	for FUNCTION in $(dirname "$0")/$DIR/*; do
		# skip directories
		if [[ -d $FUNCTION ]]; then
			continue
		# exclude markdown readmes
		elif [[ $FUNCTION == *.md ]]; then
			continue
		elif [[ -f $FUNCTION ]]; then
			# source the function file
            echo $FUNCTION
			source $FUNCTION
		fi
	done
}

